SET SERVEROUTPUT ON;
SET VERIFY OFF;
ACCEPT S_ECODE CHAR PROMPT 'Enter Employee Code : '
DECLARE
    V_ENAME EMP.ENAME%TYPE;
BEGIN
    SELECT ENAME INTO V_ENAME FROM EMP WHERE ECODE='&S_ECODE';
    DBMS_OUTPUT.PUT_LINE('Employee Name : '||V_ENAME);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EMPLOYEE WITH ID : &S_ECODE.');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/