SET SERVEROUTPUT ON;
SET VERIFY OFF;
ACCEPT T_ECODE CHAR PROMPT 'Employee Code : '
ACCEPT T_ENAME CHAR PROMPT 'Employee Name : '
ACCEPT T_DCODE CHAR PROMPT 'Department Code : '
ACCEPT T_GRADE CHAR PROMPT 'Grade : '
ACCEPT T_BASIC NUMBER PROMPT 'Basic Salary : '
ACCEPT T_JNDT CHAR PROMPT 'Joining Date (DD-MON-YYYY) : '
DECLARE
    VAR_COUNT NUMBER;
    DUPLICATE_EMP EXCEPTION;
    DEPT_NOT_EXISTS EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO VAR_COUNT FROM EMP WHERE ECODE='&T_ECODE';
    IF VAR_COUNT>0 THEN
        RAISE DUPLICATE_EMP;
    ELSE
        SELECT COUNT(*) INTO VAR_COUNT FROM DEPT WHERE DCODE='&T_DCODE';
        IF VAR_COUNT=0 THEN
            RAISE DEPT_NOT_EXISTS;
        ELSE
            INSERT INTO EMP VALUES('&T_ECODE','&T_ENAME','&T_DCODE','&T_GRADE',&T_BASIC,TO_DATE('&T_JNDT','DD-MON-YYYY'));
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('RECORD INSERTED.');
        END IF;
    END IF;
EXCEPTION 
    WHEN DUPLICATE_EMP THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE EXISTS WITH ECODE : &T_ECODE.');
    WHEN DEPT_NOT_EXISTS THEN
        DBMS_OUTPUT.PUT_LINE('DEPATMENT DOES NOT EXISTS WITH DCODE : &T_DCODE.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/