SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
    VAR_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO VAR_COUNT FROM EMP;
    IF VAR_COUNT<5 THEN
        FOR R IN (SELECT * FROM EMP) LOOP
            DBMS_OUTPUT.PUT_LINE(RPAD(R.ENAME,20)||' '||R.BASIC);
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('TABLE HAVE '||VAR_COUNT||' ROWS.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('TOP 5 EMPLOYEES');
        FOR R IN ( SELECT * FROM ( SELECT ENAME, BASIC FROM EMP ORDER BY BASIC DESC ) WHERE ROWNUM<=5) LOOP
            DBMS_OUTPUT.PUT_LINE(RPAD(R.ENAME,20)||' '||R.BASIC);
        END LOOP;
    END IF;
EXCEPTION 
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/