SET SERVEROUTPUT ON;
SET VERIFY OFF;
ACCEPT T_DCODE CHAR PROMPT 'Enter Department Code : '
DECLARE
    VAR_COUNT NUMBER;
    NO_EMP_FOUND EXCEPTION;
BEGIN
    DELETE FROM EMP WHERE DCODE='&T_DCODE';
    VAR_COUNT := SQL%ROWCOUNT;
    IF VAR_COUNT = 0 THEN
        RAISE NO_EMP_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE(VAR_COUNT || ' row(s) deleted.');
EXCEPTION
    WHEN NO_EMP_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO EMPLOYEE FOUND IN DEPARTMENT &T_DCODE.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
/