-- 0. INITIAL COMMAND
SHOW DATABASES;
USE ASSIGNMENTS;


-- 1. Minimum, Maximum and Average BASIC department wise

SELECT
    DEPT_CODE,
    MIN(BASIC) AS MIN_BASIC,
    MAX(BASIC) AS MAX_BASIC,
    AVG(BASIC) AS AVG_BASIC
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT DEPT_CODE, COUNT(*) AS TOTAL_EMP, MIN(BASIC), MAX(BASIC), AVG(BASIC) FROM EMPLOYEE GROUP BY DEPT_CODE ORDER BY DEPT_CODE;


-- 2. Number of female employees in each department

SELECT
    DEPT_CODE,
    COUNT(*) AS FEMALE_EMPLOYEES
FROM EMPLOYEE
WHERE SEX='F'
GROUP BY DEPT_CODE;



-- 3. City wise number of employees for each department

SELECT
    DEPT_CODE,
    CITY,
    COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE
GROUP BY DEPT_CODE, CITY;


-- 4. Designation wise employee count joined in year 2000
--    department wise, ascending order of count

SELECT
    E.DEPT_CODE,
    D.DESIG_DESC,
    COUNT(*) AS EMP_COUNT
FROM EMPLOYEE E
JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE
WHERE YEAR(E.JN_DT)=2000
GROUP BY E.DEPT_CODE,D.DESIG_DESC
ORDER BY EMP_COUNT ASC;

-- 5. Department wise total basic of male employees
--    Total > 50000, descending order


SELECT
    DEPT_CODE,
    SUM(BASIC) AS TOTAL_BASIC
FROM EMPLOYEE
WHERE SEX='M'
GROUP BY DEPT_CODE
HAVING SUM(BASIC) > 50000
ORDER BY TOTAL_BASIC DESC;


-- 6. Employee Name, Designation Description and Basic

SELECT
    E.EMP_NAME,
    D.DESIG_DESC,
    E.BASIC
FROM EMPLOYEE E
JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE;



-- 7. Employee Name, Designation, Department Name, Basic

SELECT
    E.EMP_NAME,
    DG.DESIG_DESC,
    DP.DEPT_NAME,
    E.BASIC
FROM EMPLOYEE E
JOIN DESIGNATION DG
    ON E.DESIG_CODE=DG.DESIG_CODE
JOIN DEPARTMENT DP
    ON E.DEPT_CODE=DP.DEPT_CODE;


-- 8. Department codes where no employee works


SELECT DEPT_CODE
FROM DEPARTMENT
WHERE DEPT_CODE NOT IN
(
    SELECT DISTINCT DEPT_CODE
    FROM EMPLOYEE
    WHERE DEPT_CODE IS NOT NULL
);

SELECT D.DEPT_CODE
FROM DEPARTMENT D
LEFT JOIN EMPLOYEE E
ON D.DEPT_CODE = E.DEPT_CODE
GROUP BY D.DEPT_CODE
HAVING COUNT(*) = 0;

-- 9. Department names where at least one employee works

SELECT DISTINCT D.DEPT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E
    ON D.DEPT_CODE=E.DEPT_CODE;



-- 10. Department names where at least 10 employees work

SELECT
    D.DEPT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E
    ON D.DEPT_CODE=E.DEPT_CODE
GROUP BY D.DEPT_CODE,D.DEPT_NAME
HAVING COUNT(*) >= 10;



-- 11. Department code where highest paid employee works

SELECT DEPT_CODE
FROM EMPLOYEE
WHERE BASIC =
(
    SELECT MAX(BASIC)
    FROM EMPLOYEE
);

SELECT DEPT_CODE FROM EMPLOYEE
ORDER BY BASIC DESC
LIMIT 1;


-- 12. Designation description of highest paid employee

SELECT D.DESIG_DESC
FROM EMPLOYEE E
JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE
WHERE E.BASIC =
(
    SELECT MAX(BASIC)
    FROM EMPLOYEE
);



-- 13. Number of managers in each department

SELECT
    E.DEPT_CODE,
    COUNT(*) AS TOTAL_MANAGERS
FROM EMPLOYEE E
JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE
WHERE D.DESIG_DESC='Manager'
GROUP BY E.DEPT_CODE;


-- 14. Maximum BASIC without using MAX()


SELECT BASIC AS MAX_BASIC
FROM EMPLOYEE
ORDER BY BASIC DESC
LIMIT 1;



-- 15. Minimum BASIC without using MIN()


SELECT BASIC AS MIN_BASIC
FROM EMPLOYEE
ORDER BY BASIC ASC
LIMIT 1;


-- 16(A). Department with highest total basic

SELECT D.DEPT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E
ON D.DEPT_CODE=E.DEPT_CODE
GROUP BY D.DEPT_CODE,D.DEPT_NAME
ORDER BY SUM(E.BASIC) DESC
LIMIT 1;

SELECT DEPT_NAME FROM DEPARTMENT NATURAL JOIN EMPLOYEE GROUP BY DEPT_CODE ORDER BY SUM(BASIC) DESC LIMIT 1;

-- 16(B). Department with highest average basic

SELECT D.DEPT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E
ON D.DEPT_CODE=E.DEPT_CODE
GROUP BY D.DEPT_CODE,D.DEPT_NAME
ORDER BY AVG(E.BASIC) DESC
LIMIT 1;


-- 16(C). Department with maximum employees

SELECT D.DEPT_NAME
FROM DEPARTMENT D
JOIN EMPLOYEE E
    ON D.DEPT_CODE=E.DEPT_CODE
GROUP BY D.DEPT_CODE,D.DEPT_NAME
ORDER BY COUNT(*) DESC
LIMIT 1;



-- 17. Insert rows with invalid designation code
-- Only works if foreign key constraint removed/disabled

--foreign key drop command
-- Format : SHOW CREATE TABLE table_name;
-- output : 
-- CONSTRAINT `employee_ibfk_1`
--     FOREIGN KEY (`DEPT_CODE`)
--     REFERENCES `department` (`DEPT_CODE`)

-- CONSTRAINT `employee_ibfk_2`
--     FOREIGN KEY (`DESIG_CODE`)
--     REFERENCES `designation` (`DESIG_CODE`)

-- Format : ALTER TABLE table_name DROP FOREIGN KEY constraint_name;

ALTER TABLE employee
DROP FOREIGN KEY employee_ibfk_1,
DROP FOREIGN KEY employee_ibfk_2;


INSERT INTO EMPLOYEE
VALUES
('E100','Test User','DP001','D999','M',
 'ABC Road','Kolkata','WB','700001',
 30000,'2024-01-01');



-- 18. Delete rows having invalid DESIG_CODE


DELETE FROM EMPLOYEE
WHERE DESIG_CODE NOT IN
(
    SELECT DESIG_CODE
    FROM DESIGNATION
);



-- 19. Female employees whose BASIC is greater than
--     average BASIC of their department


SELECT
    E1.EMP_NAME
FROM EMPLOYEE E1
WHERE E1.SEX='F'
AND E1.BASIC >
(
    SELECT AVG(E2.BASIC)
    FROM EMPLOYEE E2
    WHERE E2.DEPT_CODE=E1.DEPT_CODE
);


-- 20. Number of female managers

SELECT COUNT(*) AS FEMALE_MANAGERS
FROM EMPLOYEE E
JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE
WHERE E.SEX='F'
AND D.DESIG_DESC='Manager';